/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.practica2ipc1.frames;

import com.robertob.practica2ipc1.engine.*;
import javax.swing.JButton;

/**
 *
 * @author robertob
 */
public class MainFrame extends javax.swing.JFrame {

    public final MainEngine mainEngine = new MainEngine();
    StoreFrame storeFrame = new StoreFrame(mainEngine, this);
    ExitGameConfirmFrame exitConfirmFrame = new ExitGameConfirmFrame();
    AboutFrame aboutFrame = new AboutFrame();
    
    public MainFrame() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPetsTitle = new javax.swing.JLabel();
        petsCount = new javax.swing.JLabel();
        pet1Btn = new javax.swing.JButton();
        pet2Btn = new javax.swing.JButton();
        pet3Btn = new javax.swing.JButton();
        pet4Btn = new javax.swing.JButton();
        pet5Btn = new javax.swing.JButton();
        pet6Btn = new javax.swing.JButton();
        pet7Btn = new javax.swing.JButton();
        pet8Btn = new javax.swing.JButton();
        pet9Btn = new javax.swing.JButton();
        pet10Btn = new javax.swing.JButton();
        storeBtn = new javax.swing.JButton();
        petStatsTitle = new javax.swing.JLabel();
        typeTitle = new javax.swing.JLabel();
        nickTitle = new javax.swing.JLabel();
        levelTitle = new javax.swing.JLabel();
        foodRequestsTitle = new javax.swing.JLabel();
        dirtinessTitle = new javax.swing.JLabel();
        walkRequestsTitle = new javax.swing.JLabel();
        petImage = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        nickLabel = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        foodRequestsLabel = new javax.swing.JLabel();
        dirtinessLabel = new javax.swing.JLabel();
        walkRequestsLabel = new javax.swing.JLabel();
        cleanBtn = new javax.swing.JButton();
        cureBtn = new javax.swing.JButton();
        walkBtn = new javax.swing.JButton();
        reviveBtn = new javax.swing.JButton();
        mainMenuBar = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        storeMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitGameMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        howPlayMenuItem = new javax.swing.JMenuItem();
        reportsMenu = new javax.swing.JMenu();
        aboutMenu = new javax.swing.JMenu();
        openAboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        myPetsTitle.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        myPetsTitle.setText("MIS MASCOTAS");

        petsCount.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N

        pet1Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet1Btn.setText("Sin Mascota");
        pet1Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet1Btn.setContentAreaFilled(false);
        pet1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet1BtnActionPerformed(evt);
            }
        });

        pet2Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet2Btn.setText("Sin Mascota");
        pet2Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet2Btn.setContentAreaFilled(false);
        pet2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet2BtnActionPerformed(evt);
            }
        });

        pet3Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet3Btn.setText("Sin Mascota");
        pet3Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet3Btn.setContentAreaFilled(false);
        pet3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet3BtnActionPerformed(evt);
            }
        });

        pet4Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet4Btn.setText("Sin Mascota");
        pet4Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet4Btn.setContentAreaFilled(false);
        pet4Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet4BtnActionPerformed(evt);
            }
        });

        pet5Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet5Btn.setText("Sin Mascota");
        pet5Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet5Btn.setContentAreaFilled(false);
        pet5Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet5BtnActionPerformed(evt);
            }
        });

        pet6Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet6Btn.setText("Sin Mascota");
        pet6Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet6Btn.setContentAreaFilled(false);
        pet6Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet6Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet6BtnActionPerformed(evt);
            }
        });

        pet7Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet7Btn.setText("Sin Mascota");
        pet7Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet7Btn.setContentAreaFilled(false);
        pet7Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet7Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet7BtnActionPerformed(evt);
            }
        });

        pet8Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet8Btn.setText("Sin Mascota");
        pet8Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet8Btn.setContentAreaFilled(false);
        pet8Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet8Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet8BtnActionPerformed(evt);
            }
        });

        pet9Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet9Btn.setText("Sin Mascota");
        pet9Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet9Btn.setContentAreaFilled(false);
        pet9Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet9Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet9BtnActionPerformed(evt);
            }
        });

        pet10Btn.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        pet10Btn.setText("Sin Mascota");
        pet10Btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        pet10Btn.setContentAreaFilled(false);
        pet10Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pet10Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pet10BtnActionPerformed(evt);
            }
        });

        storeBtn.setBackground(new java.awt.Color(102, 102, 102));
        storeBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        storeBtn.setForeground(new java.awt.Color(255, 255, 255));
        storeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/storeIconSym.png"))); // NOI18N
        storeBtn.setText(" ABRIR TIENDA");
        storeBtn.setBorderPainted(false);
        storeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });

        petStatsTitle.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        petStatsTitle.setText("ESTADISTICAS DE LA MASCOTA");

        typeTitle.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        typeTitle.setText("Tipo:");

        nickTitle.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        nickTitle.setText("Apodo:");

        levelTitle.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        levelTitle.setText("Nivel:");

        foodRequestsTitle.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        foodRequestsTitle.setText("Veces que ha pedido comer:");

        dirtinessTitle.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        dirtinessTitle.setText("Excreciones:");

        walkRequestsTitle.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        walkRequestsTitle.setText("Veces que ha pedido paseo:");

        petImage.setText("imagen");
        petImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        petImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        typeLabel.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        typeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        nickLabel.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        nickLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        levelLabel.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        levelLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        foodRequestsLabel.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        foodRequestsLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        dirtinessLabel.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        dirtinessLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        walkRequestsLabel.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        walkRequestsLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        cleanBtn.setBackground(new java.awt.Color(0, 102, 102));
        cleanBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        cleanBtn.setForeground(new java.awt.Color(255, 255, 255));
        cleanBtn.setText("LIMPIAR");
        cleanBtn.setBorderPainted(false);
        cleanBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cleanBtn.setEnabled(false);
        cleanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanBtnActionPerformed(evt);
            }
        });

        cureBtn.setBackground(new java.awt.Color(0, 102, 102));
        cureBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        cureBtn.setForeground(new java.awt.Color(255, 255, 255));
        cureBtn.setText("CURAR");
        cureBtn.setBorderPainted(false);
        cureBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cureBtn.setEnabled(false);

        walkBtn.setBackground(new java.awt.Color(0, 102, 102));
        walkBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        walkBtn.setForeground(new java.awt.Color(255, 255, 255));
        walkBtn.setText("PASEAR");
        walkBtn.setBorderPainted(false);
        walkBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        walkBtn.setEnabled(false);

        reviveBtn.setBackground(new java.awt.Color(0, 102, 102));
        reviveBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        reviveBtn.setForeground(new java.awt.Color(255, 255, 255));
        reviveBtn.setText("REVIVIR");
        reviveBtn.setBorderPainted(false);
        reviveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reviveBtn.setEnabled(false);

        gameMenu.setText("Juego");

        storeMenuItem.setFont(new java.awt.Font("Cantarell", 0, 19)); // NOI18N
        storeMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/storeIconSymBlack.png"))); // NOI18N
        storeMenuItem.setText(" Abrir tienda...");
        storeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(storeMenuItem);
        gameMenu.add(jSeparator1);

        exitGameMenuItem.setFont(new java.awt.Font("Cantarell", 0, 19)); // NOI18N
        exitGameMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/exitIconSymBlack.png"))); // NOI18N
        exitGameMenuItem.setText(" Salir del juego...");
        exitGameMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameMenuItemActionPerformed(evt);
            }
        });
        gameMenu.add(exitGameMenuItem);

        mainMenuBar.add(gameMenu);

        helpMenu.setText("Ayuda");

        howPlayMenuItem.setFont(new java.awt.Font("Cantarell", 0, 19)); // NOI18N
        howPlayMenuItem.setText("?  Como jugar");
        helpMenu.add(howPlayMenuItem);

        mainMenuBar.add(helpMenu);

        reportsMenu.setText("Reportes");
        mainMenuBar.add(reportsMenu);

        aboutMenu.setText("Acerca De");

        openAboutMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/informationIconBlack.png"))); // NOI18N
        openAboutMenuItem.setText("  Ver acerca de");
        openAboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openAboutMenuItemActionPerformed(evt);
            }
        });
        aboutMenu.add(openAboutMenuItem);

        mainMenuBar.add(aboutMenu);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(petStatsTitle)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(myPetsTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(petsCount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(storeBtn)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typeTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nickTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(levelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foodRequestsTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(foodRequestsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dirtinessTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dirtinessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(walkRequestsTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(walkRequestsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(petImage, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cleanBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cureBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(walkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reviveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pet1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(pet2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pet5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(myPetsTitle)
                        .addComponent(storeBtn))
                    .addComponent(petsCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pet3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pet6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addComponent(petStatsTitle)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(typeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nickTitle)
                            .addComponent(nickLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(levelTitle)
                            .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(foodRequestsTitle)
                            .addComponent(foodRequestsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dirtinessTitle)
                            .addComponent(dirtinessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(walkRequestsTitle)
                            .addComponent(walkRequestsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cleanBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cureBtn)
                                .addGap(18, 18, 18)
                                .addComponent(walkBtn)
                                .addGap(18, 18, 18)
                                .addComponent(reviveBtn))
                            .addComponent(petImage, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void updateNickOnBtns(){
        if(mainEngine.player.getPlayerPets(0) != null){
            pet1Btn.setText(mainEngine.player.getPlayerPets(0).getNick());
            pet1Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(1) != null){
            pet2Btn.setText(mainEngine.player.getPlayerPets(1).getNick());
            pet2Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(2) != null){
            pet3Btn.setText(mainEngine.player.getPlayerPets(2).getNick());
            pet3Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(3) != null){
            pet4Btn.setText(mainEngine.player.getPlayerPets(3).getNick());
            pet4Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(4) != null){
            pet5Btn.setText(mainEngine.player.getPlayerPets(4).getNick());
            pet5Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(5) != null){
            pet6Btn.setText(mainEngine.player.getPlayerPets(5).getNick());
            pet6Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(6) != null){
            pet7Btn.setText(mainEngine.player.getPlayerPets(6).getNick());
            pet7Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(7) != null){
            pet8Btn.setText(mainEngine.player.getPlayerPets(7).getNick());
            pet8Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(8) != null){
            pet9Btn.setText(mainEngine.player.getPlayerPets(8).getNick());
            pet9Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
        if(mainEngine.player.getPlayerPets(9) != null){
            pet10Btn.setText(mainEngine.player.getPlayerPets(9).getNick());
            pet10Btn.setFont(new java.awt.Font("Cantarell", 1, 20));
        }
    
    }
    
    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
        storeFrame.setVisible(true);
    }//GEN-LAST:event_storeBtnActionPerformed

    private void storeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeMenuItemActionPerformed
        storeFrame.setVisible(true);
    }//GEN-LAST:event_storeMenuItemActionPerformed

    private void exitGameMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameMenuItemActionPerformed
        exitConfirmFrame.setVisible(true);
    }//GEN-LAST:event_exitGameMenuItemActionPerformed

    private void openAboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openAboutMenuItemActionPerformed
        aboutFrame.setVisible(true);
    }//GEN-LAST:event_openAboutMenuItemActionPerformed

    private void cleanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanBtnActionPerformed

    private void pet1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet1BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet1BtnActionPerformed

    private void pet2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet2BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet2BtnActionPerformed

    private void pet3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet3BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet3BtnActionPerformed

    private void pet4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet4BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet4BtnActionPerformed

    private void pet5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet5BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet5BtnActionPerformed

    private void pet6BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet6BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet6BtnActionPerformed

    private void pet7BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet7BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet7BtnActionPerformed

    private void pet8BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet8BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet8BtnActionPerformed

    private void pet9BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet9BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet9BtnActionPerformed

    private void pet10BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pet10BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pet10BtnActionPerformed

    public JButton getPet1Btn() {
        return pet1Btn;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutMenu;
    private javax.swing.JButton cleanBtn;
    private javax.swing.JButton cureBtn;
    private javax.swing.JLabel dirtinessLabel;
    private javax.swing.JLabel dirtinessTitle;
    private javax.swing.JMenuItem exitGameMenuItem;
    private javax.swing.JLabel foodRequestsLabel;
    private javax.swing.JLabel foodRequestsTitle;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem howPlayMenuItem;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel levelTitle;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JLabel myPetsTitle;
    private javax.swing.JLabel nickLabel;
    private javax.swing.JLabel nickTitle;
    private javax.swing.JMenuItem openAboutMenuItem;
    private javax.swing.JButton pet10Btn;
    private javax.swing.JButton pet1Btn;
    private javax.swing.JButton pet2Btn;
    private javax.swing.JButton pet3Btn;
    private javax.swing.JButton pet4Btn;
    private javax.swing.JButton pet5Btn;
    private javax.swing.JButton pet6Btn;
    private javax.swing.JButton pet7Btn;
    private javax.swing.JButton pet8Btn;
    private javax.swing.JButton pet9Btn;
    private javax.swing.JLabel petImage;
    private javax.swing.JLabel petStatsTitle;
    private javax.swing.JLabel petsCount;
    private javax.swing.JMenu reportsMenu;
    private javax.swing.JButton reviveBtn;
    private javax.swing.JButton storeBtn;
    private javax.swing.JMenuItem storeMenuItem;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel typeTitle;
    private javax.swing.JButton walkBtn;
    private javax.swing.JLabel walkRequestsLabel;
    private javax.swing.JLabel walkRequestsTitle;
    // End of variables declaration//GEN-END:variables
}
