/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.practica2ipc1.frames;

import com.robertob.practica2ipc1.engine.consumables.*;
import com.robertob.practica2ipc1.engine.MainEngine;
import com.robertob.practica2ipc1.engine.character.*;
import javax.swing.DefaultListModel;

/**
 *
 * @author robertob
 */
public class PetSelector extends javax.swing.JFrame {

    MainEngine mainEngine;
    DefaultListModel petsListModel = new DefaultListModel();
    Pet selectedPet;
    String itemName;
    
    public PetSelector(MainEngine mainEngine) {
        initComponents();
        this.mainEngine = mainEngine;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorTitle = new javax.swing.JLabel();
        itemNameSelector = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        giveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        petSelectorList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        selectorTitle.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        selectorTitle.setText("¿A qué mascota quieres darle: ");

        itemNameSelector.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        itemNameSelector.setText(" ");

        cancelBtn.setBackground(new java.awt.Color(102, 102, 102));
        cancelBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/cancelIcon.png"))); // NOI18N
        cancelBtn.setText(" CANCELAR");
        cancelBtn.setBorderPainted(false);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        giveBtn.setBackground(new java.awt.Color(51, 255, 204));
        giveBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        giveBtn.setForeground(new java.awt.Color(255, 255, 255));
        giveBtn.setText("DAR OBJETO");
        giveBtn.setBorderPainted(false);
        giveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        giveBtn.setEnabled(false);
        giveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giveBtnActionPerformed(evt);
            }
        });

        petSelectorList.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        petSelectorList.setModel(petsListModel);
        petSelectorList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petSelectorListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(petSelectorList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(cancelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(giveBtn)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(selectorTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemNameSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTitle)
                    .addComponent(itemNameSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn)
                    .addComponent(giveBtn))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void updateNickOnList(){
        
        this.petsListModel.removeAllElements();
        for (int i = 0; i < 10; i++) {
            if(mainEngine.player.getPlayerPets(i) != null){
                petsListModel.addElement(mainEngine.player.getPlayerPets(i).getNick());
            };
        }
        this.petSelectorList.setModel(petsListModel);        
       
    }
    
    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void giveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giveBtnActionPerformed
        
        switch (itemName) {
            case "Manzana":
                Food manzana = new Apple();
                manzana.boost(selectedPet);
                mainEngine.player.lowerMoney(manzana.getPrice());
                break;
            case "Cereal":
                Food cereal = new Cereal();
                cereal.boost(selectedPet);
                mainEngine.player.lowerMoney(cereal.getPrice());
                break;
            case "Waffles":
                Food waffle = new Waffle();
                waffle.boost(selectedPet);
                mainEngine.player.lowerMoney(waffle.getPrice());
                break;
            case "Vitamina":
                Med vitamin = new Vitamin();
                vitamin.boost(selectedPet);
                mainEngine.player.lowerMoney(vitamin.getPrice());
                break;
            case "Analgesico":
                Med analgesic = new Analgesic();
                analgesic.boost(selectedPet);
                mainEngine.player.lowerMoney(analgesic.getPrice());
                break;
            case "Antibiotico":
                System.out.println("vitamina");
                break;
        }
        
        this.dispose();
    }//GEN-LAST:event_giveBtnActionPerformed

    private void petSelectorListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petSelectorListMouseClicked
        try {
            selectedPet = mainEngine.player.getPlayerPets(petSelectorList.getSelectedIndex());
            giveBtn.setEnabled(true);
        } catch (ArrayIndexOutOfBoundsException aioobe) {
            System.out.println("No se selecciono mascota");
        }
        
        
    }//GEN-LAST:event_petSelectorListMouseClicked

    public void showItemLabel(String itemName){
        itemNameSelector.setText(itemName);
        giveBtn.setText(("DAR "+itemName.toUpperCase()));
        this.itemName = itemName;
    
    }
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton giveBtn;
    private javax.swing.JLabel itemNameSelector;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> petSelectorList;
    private javax.swing.JLabel selectorTitle;
    // End of variables declaration//GEN-END:variables
}
