/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.practica2ipc1.frames;

/**
 *
 * @author robertob
 */
public class PetSelector extends javax.swing.JFrame {

    /**
     * Creates new form PetSelector
     */
    public PetSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorTitle = new javax.swing.JLabel();
        itemNameSelector = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        pet1Btn = new javax.swing.JButton();
        pet2Btn = new javax.swing.JButton();
        pet3Btn = new javax.swing.JButton();
        pet4Btn = new javax.swing.JButton();
        pet5Btn = new javax.swing.JButton();
        pet6Btn = new javax.swing.JButton();
        pet7Btn = new javax.swing.JButton();
        pet8Btn = new javax.swing.JButton();
        pet9Btn = new javax.swing.JButton();
        pet10Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        selectorTitle.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N
        selectorTitle.setText("¿A qué mascota quieres darle: ");

        itemNameSelector.setFont(new java.awt.Font("Cantarell", 1, 22)); // NOI18N

        cancelBtn.setBackground(new java.awt.Color(102, 102, 102));
        cancelBtn.setFont(new java.awt.Font("Cantarell", 1, 19)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/cancelIcon.png"))); // NOI18N
        cancelBtn.setText(" CANCELAR");
        cancelBtn.setBorderPainted(false);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        pet1Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet1Btn.setText("jButton1");
        pet1Btn.setBorderPainted(false);
        pet1Btn.setContentAreaFilled(false);
        pet1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet2Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet2Btn.setText("jButton1");
        pet2Btn.setBorderPainted(false);
        pet2Btn.setContentAreaFilled(false);
        pet2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet3Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet3Btn.setText("jButton1");
        pet3Btn.setBorderPainted(false);
        pet3Btn.setContentAreaFilled(false);
        pet3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet4Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet4Btn.setText("jButton1");
        pet4Btn.setBorderPainted(false);
        pet4Btn.setContentAreaFilled(false);
        pet4Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet5Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet5Btn.setText("jButton1");
        pet5Btn.setBorderPainted(false);
        pet5Btn.setContentAreaFilled(false);
        pet5Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet6Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet6Btn.setText("jButton1");
        pet6Btn.setBorderPainted(false);
        pet6Btn.setContentAreaFilled(false);
        pet6Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet7Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet7Btn.setText("jButton1");
        pet7Btn.setBorderPainted(false);
        pet7Btn.setContentAreaFilled(false);
        pet7Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet8Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet8Btn.setText("jButton1");
        pet8Btn.setBorderPainted(false);
        pet8Btn.setContentAreaFilled(false);
        pet8Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet9Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet9Btn.setText("jButton1");
        pet9Btn.setBorderPainted(false);
        pet9Btn.setContentAreaFilled(false);
        pet9Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        pet10Btn.setFont(new java.awt.Font("Cantarell", 0, 21)); // NOI18N
        pet10Btn.setText("jButton1");
        pet10Btn.setBorderPainted(false);
        pet10Btn.setContentAreaFilled(false);
        pet10Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(selectorTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemNameSelector)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pet6Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet7Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet8Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet9Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet10Btn))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pet1Btn)
                            .addGap(12, 12, 12)
                            .addComponent(pet2Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet3Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet4Btn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(pet5Btn)))
                    .addComponent(cancelBtn))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectorTitle)
                    .addComponent(itemNameSelector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pet1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet3Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet4Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet5Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pet6Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet7Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet8Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet9Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pet10Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel itemNameSelector;
    private javax.swing.JButton pet10Btn;
    private javax.swing.JButton pet1Btn;
    private javax.swing.JButton pet2Btn;
    private javax.swing.JButton pet3Btn;
    private javax.swing.JButton pet4Btn;
    private javax.swing.JButton pet5Btn;
    private javax.swing.JButton pet6Btn;
    private javax.swing.JButton pet7Btn;
    private javax.swing.JButton pet8Btn;
    private javax.swing.JButton pet9Btn;
    private javax.swing.JLabel selectorTitle;
    // End of variables declaration//GEN-END:variables
}
