/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.robertob.practica2ipc1.frames;

import com.robertob.practica2ipc1.engine.MainEngine;

/**
 *
 * @author robertob
 */
public class WelcomeFrame extends javax.swing.JFrame {
    
    
    /**
     * Creates new form WelcomeFrame
     */
    public WelcomeFrame() {
        initComponents();
    }
    
    MainFrame mainFrame = new MainFrame();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        welcomeTitle = new javax.swing.JLabel();
        welcomeTitle1 = new javax.swing.JLabel();
        welcomeTitle2 = new javax.swing.JLabel();
        exitWelcomeBtn = new javax.swing.JButton();
        startWelcomeBtn = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Iniciar Juego");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        welcomeTitle.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        welcomeTitle.setText("¡Bienvenid@ al juego!");

        welcomeTitle1.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        welcomeTitle1.setText("o presiona \"Salir\" para salir del juego");

        welcomeTitle2.setFont(new java.awt.Font("Cantarell", 0, 24)); // NOI18N
        welcomeTitle2.setText("Presiona el botón de abajo para empezar,");

        exitWelcomeBtn.setBackground(new java.awt.Color(255, 204, 204));
        exitWelcomeBtn.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        exitWelcomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/exitIconSymBlack.png"))); // NOI18N
        exitWelcomeBtn.setText(" SALIR");
        exitWelcomeBtn.setBorderPainted(false);
        exitWelcomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitWelcomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitWelcomeBtnActionPerformed(evt);
            }
        });

        startWelcomeBtn.setBackground(new java.awt.Color(0, 255, 204));
        startWelcomeBtn.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        startWelcomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/robertob/practica2ipc1/images/playIcon.png"))); // NOI18N
        startWelcomeBtn.setText(" INICIAR");
        startWelcomeBtn.setBorderPainted(false);
        startWelcomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startWelcomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startWelcomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(welcomeTitle)
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeTitle2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(startWelcomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitWelcomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(welcomeTitle1)
                            .addGap(18, 18, 18))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(welcomeTitle)
                .addGap(64, 64, 64)
                .addComponent(welcomeTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeTitle1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startWelcomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitWelcomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitWelcomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitWelcomeBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitWelcomeBtnActionPerformed

    private void startWelcomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startWelcomeBtnActionPerformed
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_startWelcomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitWelcomeBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton startWelcomeBtn;
    private javax.swing.JLabel welcomeTitle;
    private javax.swing.JLabel welcomeTitle1;
    private javax.swing.JLabel welcomeTitle2;
    // End of variables declaration//GEN-END:variables
}
